### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by Grokzen** [felskrone/salt-eventsd#22]
Hi. I know you have stated that you do not want to maintain multiple package builds like pypi, deb, rpm etc... but i think you should really reconsider to atleast upload this package to pypi so it can be easily installed via pip.

I have found this very easy and useful guide how to upload a package to pypi http://peterdowns.com/posts/first-time-with-pypi.html

In the end when you have the proper setup and config on your system, uploading a new release is as easy as `python setup.py sdist upload -r pypi` and it is done.

The PR #21 is intended for this issue and to make it work better when uploaded to pypi.

**Comment by felskrone** [comment]
Done :-)
