### ISSUE TITLE
 First event not pushed when event_limit > 1

### ISSUE THREAD

**Issue by Grokzen** [felskrone/salt-eventsd#29]
I hope i got this reliably reproducable. Tested on `Tag: 0.9.1`

Use the workers and config that exists in `doc/` but set `event_limit=10` and `dump_timer=5`.

Then have a salt-master and minion on the same machine and run `salt <machine_id> test.ping` and watch the output in `EVD` and wait 5 seconds for the time to trigger. And nothing happens and no events is emited out from `EVD`.

I think the main problem is that the timer do not fire even if there is events in the queue and this can cause problems if any number of events is stuck in the queue and nothing happens until next event is sent in.

**Comment by Grokzen** [comment]
I think i have narrowed down the main issue of this.

In the big main while loop in `listen()` i think there is a logic flaw that prevents the events to be emited.

Currently the logic is to listen for a event on the zmq event bus and when that returns `None` ever other second the first thing that is checked is if there was any event returned and sinc there was none then we get to a `continue` statement that just drops us back to zmq event bus to listen for another event again.

So if we have the above case where we have more a queue > 1 then at the first time the a event is found then it is put in the queue but sinc the timer have not reset or the event limit is reached then it will just sit in there until the next event comes in and it can fix the problem.

I think that a closer look at the `listen()` loop logic has to be done in order to fix this problem.

**Comment by felskrone** [comment]
Good catch! Thanks! :-)
