### ISSUE TITLE
Add support for elasticsearch output

### ISSUE THREAD

**Issue by viq** [felskrone/salt-eventsd#32]
Elasticsearch output would be great, because then it would be trivial to use kibana to access the logs and get statistics, whereas with other outputs you'd need to prepare something yourself.

https://github.com/comperiosearch/vagrant-elk-box seems to be an OK sample of elasticsearch with kibana, with logstash in the mix if you want to try that. Please poke me on IRC if there's anything I can assist with.

**Comment by felskrone** [comment]
Thats exactly what i asked for on IRC a while ago. I will try checking it out this week!

**Comment by viq** [comment]
Well, what do you know, apparently someone already did some work towads this at https://github.com/llnw/salt-eventsd/commit/f5a26bf2ad18d57df86d2ce04eba569986b7fd83

**Comment by felskrone** [comment]
Sorry that i have not come around to testing this out. The days are just too short with 24 hours :-/

That worker looks very nice. I will happily merge it in a PR!

**Comment by viq** [comment]
@jasonhancock / @kev009 are you planning to make a pull request out of your work? ;)

**Comment by felskrone** [comment]
I pinged him again in the commit where he added the worker to his own fork.

**Comment by jasonhancock** [comment]
PR submitted: https://github.com/felskrone/salt-eventsd/pull/39

**Comment by felskrone** [comment]
I merged it locally and its running in my test-env. Will be published with some other work shortly :-)

**Comment by felskrone** [comment]
Its in 0.9.3 being release in a few minutes.
