### ISSUE TITLE
KeyError: 'fun' when using subevents

### ISSUE THREAD

**Issue by syphernl** [felskrone/salt-eventsd#41]
Once in a while the following error comes around:

```
[DEBUG   ] resetting the Event-timer
Exception in thread 2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.7/salteventsd/worker.py", line 40, in run
    self._store_data()
  File "/usr/lib/pymodules/python2.7/salteventsd/worker.py", line 102, in _store_data
    if self.event_map[event]['subs'][subevent]['tag'].match(entry['data']['fun']):
KeyError: 'fun'
```

This is most likely due to the fact that there is a difference between returns from a command (`salt '*' test.foo`, `salt-call test.foo`) and by a scheduler.

**Comment by felskrone** [comment]
Could you add the two different event formats?

**Comment by syphernl** [comment]
For that I'll need to patch eventsd so it shows what it actually receives as it doesn't reach my workers (which also output that for debugging purposes).

**Comment by felskrone** [comment]
You can run

```bash
 salt-run state.event pretty=True
```

on your master to see all the events being fired on the eventbus without hacking anything :-)

I dont need the pretty=True parameter.

**Comment by syphernl** [comment]
Hmm true. Could've also used the eventlistener.py script. 
Will grab some comparison events tomorrow morning when I'm back at the office.

**Comment by syphernl** [comment]
Hmm, seems like this may be a problem with my returner (due to the fact Salt puts the event data (fired by `event.fire_master`) in the `data` key:

salt-call state.highstate (minion initated):
```
salt/job/20150310081250284516/ret/vm.example.com	{
    "_stamp": "2015-03-10T08:12:50.288505", 
    "arg": [], 
    "cmd": "_return", 
    "fun": "state.highstate", 
    "fun_args": [], 
    "id": "vm.example.com", 
    "jid": "20150310081250284516", 
    "out": "highstate", 
    "retcode": 0, 
    "return": { /* removed */ }, 
    "success": true, 
    "tgt": "vm.example.com", 
    "tgt_type": "glob"
}
```

salt 'vm.example.com' state.highstate (master initiated):
```
salt/job/20150310081413366875/ret/vm.example.com	{
    "_stamp": "2015-03-10T08:14:24.153806", 
    "cmd": "_return", 
    "fun": "state.highstate", 
    "fun_args": [], 
    "id": "vm.example.com", 
    "jid": "20150310081413366875", 
    "out": "highstate", 
    "retcode": 0, 
    "return": { /* removed */ }, 
    "success": true
}
```

Scheduler event (master enforced, minion initiated):
```
salt/job/20150310072436363068/ret/vm.example.com	{
    "_stamp": "2015-03-10T08:24:43.475106", 
    "cmd": "_minion_event", 
    "data": {
        "fun": "state.highstate", 
        "id": "vm.example.com", 
        "jid": "20150310072436363068", 
        "pid": 22495, 
        "return": { /* removed */ }, 
    "id": "vm.example.com", 
    "pretag": null, 
    "tag": "salt/job/20150310072436363068/ret/vm.example.com"
}
```

After minion restart:
```
salt/job/20150310073346643550/ret/vm.example.com	{
    "_stamp": "2015-03-10T08:33:52.635025", 
    "cmd": "_minion_event", 
    "data": {
        "fun": "state.highstate", 
        "id": "vm.example.com", 
        "jid": "20150310073346643550", 
        "pid": 22831, 
        "return": { /* removed */ }, 
    "id": "vm.example.com
", 
    "pretag": null, 
    "tag": "salt/job/20150310073346643550/ret/vm.example.com"
}
```

**Comment by syphernl** [comment]
I have tried to modify the Salt events module to move the data to the first level but haven't been able to do this yet.

Could this be handled in eventsd? Checking if there is a data and if its has a `fun` and use that or even better: flatten the dictionary (move everything from `data` to the first level?) 

In my workers I have been able to work around that problem, but the `fun` issue hits eventsd at a higher level.

**Comment by felskrone** [comment]
Thanks for the events. But there is definately a handling error in the daemon itself. In that line of code nothing has been handed to the worker yet. Its trying to figure out, to what worker the data should be forwarded to.

From the top of my head i think this is what happens:

1. There is event A that has a subevent configured.
2. The daemon matches on event A by tag.
3. Once the event_limit is reached, the collected events are forwarded to the part of the code, where the matching to the actual workers takes place.
4. Thats where the daemon checks if event A has subevents configured. If it does, the collected events are further inspected by looking at the fun field. Thats where the above trace happens because one of the collected A-events has a subevent configured, but the event itself does not contain a fun-field.

If the above are all the events that occure, which one of them triggers the error?

By looking at the different formats (1+2 are the same and 3+4 are the same).

**Comment by syphernl** [comment]
1+2 are returns given by Salt, 3+4 are via the Salt eventbus (`event.fire_master`). 
It seems that it does not allow any changes to the files and "forces" the data to be in `data`). I've tried to add a custom key as a test but it was never transmitted.

In the main event (in eventsd) this works fine. In my code I have a check that handles that. 
But with sub-events eventsd requires a key (`fun`) that is not at the first level like in the first two events (which are returns by Salt itself whereas 3+4 are via `event.fire_master`) but is nested in `data`.

Another option would be to (also) check for the existence of the `_minion_event` in `cmd` since those responses will always be (partially) in `data`.

**Comment by felskrone** [comment]
Fixed in develop.

**Comment by syphernl** [comment]
Verified!
