### ISSUE TITLE
Add logrotate

### ISSUE THREAD

**Issue by syphernl** [felskrone/salt-eventsd#43]
The log for eventsd may grow very big, even with "normal" output and not even with debug:
```
total 501M
drwxr-xr-x  2 root root   4,0K mrt 19 06:45 .
drwxrwxr-x 14 root syslog 4,0K mrt 19 06:45 ..
-rw-r--r--  1 root root   500M mrt 19 12:31 eventsd
```

It is perhaps a good idea to add logrotate configuration (e.g. `/etc/logrotate.d/salt-eventsd`) to the package to prevent this from happening. 

Same for Salt itself, a 7-day rotate should suffice:

```
/var/log/salt/eventsd {
	weekly
	missingok
	rotate 7
	compress
	notifempty
}
```

**Comment by felskrone** [comment]
The logrotation was already provided by Jason Hancocks PR with the elastic-search worker, sorry :-/
